### ISSUE TITLE
Travis failed building jul with the following bug in a unit test

### ISSUE THREAD

**Issue by pLeminoq** [openbase/jul#14]
<pre>
Running org.openbase.jul.extension.rsb.com.RSBCommunicationServiceTest
17:04:54.573 [main] INFO  o.o.j.p.JPVerbose Verbose is enabled!
17:04:54.577 [main] INFO  o.o.j.p.JPTestMode Test mode enabled!
17:04:54.988 [Thread-1] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest$RSBRemoteServiceImpl Remote connection to Controller[/test/reconnection/] was detached because the controller shutdown was initiated.
17:04:54.991 [Time-limited test] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest Disable inprocess communication during tests.
17:04:54.992 [Time-limited test] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest Enable inprocess communication during tests.
17:04:54.992 [Time-limited test] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest Enabled: inprocess
17:04:55.015 [Thread-10] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest$RSBRemoteServiceImpl Remote connection to Controller[/test/reconnection/] was detached because the controller shutdown was initiated.
17:04:55.045 [Time-limited test] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest Wait for data sync
17:04:55.048 [Thread-21] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest$RSBRemoteServiceImpl Remote connection to Controller[/test/synchronization/] was detached because the controller shutdown was initiated.
17:04:55.050 [pool-1-thread-37] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest$RSBRemoteServiceImpl Connection reestablished RSBRemoteServiceImpl[scope:/test/synchronization/]
17:04:55.058 [Thread-21] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest$RSBRemoteServiceImpl Remote connection to Controller[/test/synchronization/] was detached because the controller shutdown was initiated.
17:05:00.063 [Thread-21] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest$RSBRemoteServiceImpl Connection reestablished RSBRemoteServiceImpl[scope:/test/synchronization/]
17:05:00.063 [pool-1-thread-46] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest$RSBRemoteServiceImpl Wait that disconnected RSBServiceImpl[/test/synchronization/] is connected...
wait for inital connection...
17:05:00.081 [Thread-30] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest$RSBRemoteServiceImpl Remote connection to Controller[/test/reconnection/] was detached because the controller shutdown was initiated.
wait for connection lost after controller shutdown...
17:05:00.086 [pool-1-thread-59] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest$RSBRemoteServiceImpl Connection reestablished RSBRemoteServiceImpl[scope:/test/reconnection/]
wait for reconnection lost after controller start...
wait for remote shutdown...
17:05:05.081 [pool-1-thread-56] WARN  o.o.j.e.r.c.RSBCommunicationServiceTest$RSBRemoteServiceImpl Remote connection to Controller[/test/reconnection/] lost!
17:05:05.081 [Time-limited test] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest$RSBRemoteServiceImpl Wait that connecting RSBServiceImpl[/test/reconnection/] is disconnected...
Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 36.119 sec <<< FAILURE!
testReconnection(org.openbase.jul.extension.rsb.com.RSBCommunicationServiceTest)  Time elapsed: 30.006 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.waitForConnectionState(RSBRemoteService.java:1014)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.waitForConnectionState(RSBRemoteService.java:1048)
	at org.openbase.jul.extension.rsb.com.RSBCommunicationServiceTest.testReconnection(RSBCommunicationServiceTest.java:218)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by DivineThreepwood** [comment]
Exception did not occurs again since the last 3 month, so hopefully already fixed. 
Otherwise reopen.
