### ISSUE TITLE
Avoid to recover the middleware if the communication shutdown was initiated

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/jul#33]
<pre>
testRestartingDeviceRegistryRemotes(org.openbase.bco.registry.mock.RemoteTest)  Time elapsed: 15.016 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 15000 milliseconds
	at org.openbase.bco.registry.mock.RemoteTest.testRestartingDeviceRegistryRemotes(RemoteTest.java:99)
12:40:37.142 [ShutdownDeamon[GlobalCachedExecutorService]] INFO  o.o.j.s.GlobalCachedExecutorService Waiting for 3 tasks to continue the shutdown.
12:40:39.143 [ShutdownDeamon[GlobalCachedExecutorService]] INFO  o.o.j.s.GlobalCachedExecutorService Waiting for 1 tasks to continue the shutdown.
12:40:48.918 [pool-1-thread-95] ERROR o.o.b.r.d.r.DeviceRegistryRemote ═╦═⚀ Recovering middleware connection failed!
12:40:48.918 [pool-1-thread-95] ERROR o.o.b.r.d.r.DeviceRegistryRemote  ╚══╦═⚀ Could not reinitialize DeviceRegistryRemote[scope:/test/travis/registry/device/]!
12:40:48.918 [pool-1-thread-95] ERROR o.o.b.r.d.r.DeviceRegistryRemote     ╚══╦═⚀ Could not reinit DeviceRegistryRemote[scope:/test/travis/registry/device/]!
12:40:48.918 [pool-1-thread-95] ERROR o.o.b.r.d.r.DeviceRegistryRemote        ╚══╦═⚀ Could not initialize class org.openbase.bco.registry.device.remote.DeviceRegistryRemote!
12:40:48.918 [pool-1-thread-95] ERROR o.o.b.r.d.r.DeviceRegistryRemote           ╚══╦═⚀ Could not initialize class org.openbase.bco.registry.device.remote.DeviceRegistryRemote!
12:40:48.918 [pool-1-thread-95] ERROR o.o.b.r.d.r.DeviceRegistryRemote              ╚══╦═⚀ Context[cached unit registry] is not available!
12:40:48.918 [pool-1-thread-95] ERROR o.o.b.r.d.r.DeviceRegistryRemote                 ╚════⚀ Remote service is shutting down!
12:40:48.918 [pool-1-thread-95] ERROR o.o.b.r.d.r.DeviceRegistryRemote =====================================
12:40:48.920 [pool-1-thread-95] ERROR o.o.b.r.d.r.DeviceRegistryRemote Recovering middleware connection failed!
org.openbase.jul.exception.CouldNotPerformException: Recovering middleware connection failed!
	at org.openbase.jul.exception.printer.ExceptionPrinter.printHistory(ExceptionPrinter.java:140)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService$1.call(RSBRemoteService.java:759)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not reinitialize DeviceRegistryRemote[scope:/test/travis/registry/device/]!
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.reinit(RSBRemoteService.java:493)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.reinit(RSBRemoteService.java:458)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService$1.call(RSBRemoteService.java:757)
	... 4 common frames omitted
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not reinit DeviceRegistryRemote[scope:/test/travis/registry/device/]!
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.reinit(RSBRemoteService.java:486)
	... 6 common frames omitted
Caused by: org.openbase.jul.exception.InitializationException: Could not initialize class org.openbase.bco.registry.device.remote.DeviceRegistryRemote!
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.internalInit(RSBRemoteService.java:247)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.reinit(RSBRemoteService.java:484)
	... 6 common frames omitted
Caused by: org.openbase.jul.exception.InitializationException: Could not initialize class org.openbase.bco.registry.device.remote.DeviceRegistryRemote!
	at org.openbase.bco.registry.device.remote.DeviceRegistryRemote.registerRegistryRemotes(DeviceRegistryRemote.java:112)
	at org.openbase.bco.registry.lib.com.AbstractVirtualRegistryRemote.postInit(AbstractVirtualRegistryRemote.java:72)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.internalInit(RSBRemoteService.java:239)
	... 7 common frames omitted
Caused by: org.openbase.jul.exception.NotAvailableException: Context[cached unit registry] is not available!
	at org.openbase.bco.registry.unit.remote.CachedUnitRegistryRemote.getRegistry(CachedUnitRegistryRemote.java:106)
	at org.openbase.bco.registry.device.remote.DeviceRegistryRemote.registerRegistryRemotes(DeviceRegistryRemote.java:109)
	... 9 common frames omitted
Caused by: org.openbase.jul.exception.InvalidStateException: Remote service is shutting down!
	at org.openbase.bco.registry.unit.remote.CachedUnitRegistryRemote.getRegistry(CachedUnitRegistryRemote.java:86)
	... 10 common frames omitted
12:40:48.920 [pool-1-thread-95] ERROR o.o.b.r.d.r.DeviceRegistryRemote =====================================
Results :
Tests in error: 
  RemoteTest.testRestartingDeviceRegistryRemotes:99->Object.wait:-2 » TestTimedOut
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] BCO Registry ....................................... SUCCESS [  0.067 s]
[INFO] BCO Registry Lib ................................... SUCCESS [  9.154 s]
[INFO] BCO Registry Device ................................ SUCCESS [  0.004 s]
[INFO] BCO Registry Device Library ........................ SUCCESS [  1.017 s]
[INFO] BCO Registry Unit .................................. SUCCESS [  0.002 s]
[INFO] BCO Registry Unit Library .......................... SUCCESS [  0.456 s]
[INFO] BCO Registry Unit Remote ........................... SUCCESS [  0.542 s]
[INFO] BCO Registry Device Core ........................... SUCCESS [  1.428 s]
[INFO] BCO Registry Device Remote ......................... SUCCESS [  0.301 s]
[INFO] BCO Registry Location .............................. SUCCESS [  0.000 s]
[INFO] BCO Registry Location Library ...................... SUCCESS [  0.298 s]
[INFO] BCO Registry Location Core ......................... SUCCESS [  1.118 s]
[INFO] BCO Registry User .................................. SUCCESS [  0.003 s]
[INFO] BCO Registry User Library .......................... SUCCESS [  0.122 s]
[INFO] BCO Registry User Core ............................. SUCCESS [  0.748 s]
[INFO] BCO Registry Device Test ........................... SUCCESS [  0.049 s]
[INFO] BCO Registry Location Remote ....................... SUCCESS [  0.313 s]
[INFO] BCO Registry App ................................... SUCCESS [  0.001 s]
[INFO] BCO Registry App Library ........................... SUCCESS [  0.094 s]
[INFO] BCO Registry App Remote ............................ SUCCESS [  0.213 s]
[INFO] BCO Registry Agent ................................. SUCCESS [  0.004 s]
[INFO] BCO Registry Agent Library ......................... SUCCESS [  0.111 s]
[INFO] BCO Registry Agent Remote .......................... SUCCESS [  0.184 s]
[INFO] BCO Registry Unit Core ............................. SUCCESS [  2.522 s]
[INFO] BCO Registry App Core .............................. SUCCESS [  0.788 s]
[INFO] BCO Registry Agent Core ............................ SUCCESS [  0.719 s]
[INFO] BCO Registry Scene ................................. SUCCESS [  0.001 s]
[INFO] BCO Registry Scene Library ......................... SUCCESS [  0.086 s]
[INFO] BCO Registry Scene Core ............................ SUCCESS [  0.646 s]
[INFO] BCO Registry Scene Remote .......................... SUCCESS [  0.131 s]
[INFO] BCO Registry User Remote ........................... SUCCESS [  0.142 s]
[INFO] BCO Registry Remote ................................ SUCCESS [  0.490 s]
[INFO] BCO Registry Utility ............................... FAILURE [ 56.949 s]
[INFO] BCO Registry Location Test ......................... SKIPPED
[INFO] BCO Registry Scene Test ............................ SKIPPED
[INFO] BCO Registry Agent Test ............................ SKIPPED
[INFO] BCO Registry App Test .............................. SKIPPED
[INFO] BCO Registry Unit Test ............................. SKIPPED
[INFO] BCO Registry User Test ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
</pre>

**Comment by pLeminoq** [comment]
I think this is already fixed. If not reopen.
