### ISSUE TITLE
RSBCommunicationServiceTest timeouts

### ISSUE THREAD

**Issue by pLeminoq** [openbase/jul#42]
The reconnection test of the RSBCommunicationServiceTest sometimes fails with a timeout. Here is an example from travis(https://travis-ci.org/openbase/jul/builds/294943622):

<pre>
testReconnection
wait for inital connection...
16:28:03.837 [Thread-28] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest$RSBRemoteServiceImpl Remote connection to Controller[/test/reconnection/] was detached because the controller shutdown was initiated.
wait for connection lost after controller shutdown...
wait for reconnection lost after controller start...
16:28:03.867 [pool-1-thread-67] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest$RSBRemoteServiceImpl Connection reestablished RSBRemoteServiceImpl[scope:/test/reconnection/]
wait for remote shutdown...
16:28:18.889 [Time-limited test] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest$RSBRemoteServiceImpl Wait for connected RSBServiceImpl[/test/reconnection/] to be disconnected...
testNotification
16:28:23.873 [Thread-33] INFO  o.o.j.e.r.c.RSBCommunicationServiceTest$RSBRemoteServiceImpl Remote connection to Controller[/test/notification/] was detached because the controller shutdown was initiated.
Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 26.911 sec <<< FAILURE!
testReconnection(org.openbase.jul.extension.rsb.com.RSBCommunicationServiceTest)  Time elapsed: 20.006 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.waitForConnectionState(RSBRemoteService.java:1109)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.waitForConnectionState(RSBRemoteService.java:1142)
	at org.openbase.jul.extension.rsb.com.RSBCommunicationServiceTest.testReconnection(RSBCommunicationServiceTest.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
</pre>

It seem like the remote does not switch to the connection state disconnected on shutdown. Commit 530f0b102d646cb498118849b6e7493b3305b6fc added additional logging to this test because I cannot reproduce this bug on the machine I am currently working on. So maybe future travis builds will be more revealing.

**Comment by pLeminoq** [comment]
Does this issue still exist?

**Comment by pLeminoq** [comment]
Seems like it did not happen again since then. If it happens again reopen.
