### ISSUE TITLE
Spread Exception kills bco completely

### ISSUE THREAD

**Issue by pLeminoq** [openbase/jul#45]
<pre>
WARNING: Caught a SpreadException while trying to receive a message
spread.SpreadException: Connection closed while reading message body
    at spread.SpreadConnection.readBytesFromSocketListener(SpreadConnection.java:340)
    at spread.SpreadConnection.internal_receive(SpreadConnection.java:1280)
    at spread.SpreadConnection.receive(SpreadConnection.java:1094)
    at rsb.transport.spread.SpreadWrapperImpl.receive(SpreadWrapperImpl.java:282)
    at rsb.transport.spread.ReceiverTask.run(ReceiverTask.java:134)
</pre>

**Comment by DivineThreepwood** [comment]
outdated
