### ISSUE TITLE
Fix unstable test - reinit

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/jul#54]
Reinit sometimes fails with:
<pre>
testReinit
Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 18.356 sec <<< FAILURE!
testReinit(org.openbase.jul.extension.rsb.com.AbstractControllerServerTest)  Time elapsed: 15.014 sec  <<< FAILURE!
java.lang.AssertionError: Reint took too long! Please analyse deadlock in stacktrace...
	at org.junit.Assert.fail(Assert.java:88)
	at org.openbase.jul.extension.rsb.com.AbstractControllerServerTest.testReinit(AbstractControllerServerTest.java:440)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:835)
</pre>

**Comment by DivineThreepwood** [comment]
blocked by: 
* https://github.com/open-rsx/rsb-java/issues/28
* https://github.com/open-rsx/rsb-java/issues/30
* https://github.com/open-rsx/rsb-java/issues/32

**Comment by DivineThreepwood** [comment]
outdated issue.
